name: ketemaa
description: Ketemaa.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  get: ^4.3.8
  dartz: ^0.10.0
  equatable: ^2.0.3
  carousel_slider: ^4.0.0
  data_connection_checker: ^0.3.4
  # http: ^0.13.4
  google_fonts: ^2.1.0
  flutter_svg: any
  lint: ^1.5.3
  flutter_image_slider: ^0.0.2
  fluttertoast: ^8.0.8
  ##firebase_crashlytics: ^2.3.0
  email_validator: ^2.0.1
  bottom_bar_page_transition: ^2.0.0
  graphql_flutter: ^5.0.0
  loading_indicator: ^3.0.2
  shared_preferences: ^2.0.8
  dropdown_plus: ^0.0.9
  shimmer:
  ##firebase_core:
  skeleton_animation: ^0.1.4
  provider: ^6.0.2
  another_flushbar: ^1.10.28
  share_plus: ^3.1.0
  rating_dialog: ^2.0.3
  store_redirect: ^2.0.1
  image_picker: ^0.8.4+9
  animated_theme_switcher: ^2.0.6
  anim_search_bar: ^2.0.2
  flutter_typeahead: ^3.2.4
  animate_do: ^2.1.0
  fl_chart: ^0.45.1
  glass_kit: ^2.0.1
  filter_list: ^1.0.1
  pie_chart: ^5.1.0
  flutter_initicon: ^2.0.0
  random_color: ^1.0.6-nullsafety
  hexcolor: ^2.0.6
  pinput: ^2.2.4
  blurrycontainer: ^0.1.0
  file_picker: ^4.5.1
  pin_code_fields: ^7.3.0
  pull_to_refresh: ^2.0.0
  syncfusion_flutter_charts: ^19.4.56
  dropdown_button2: ^1.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:


  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/media/image/
    - assets/media/icon/
    - assets/media/slider/


